# CONSTANTS:
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 1000
LEFT_LIMIT = 100
RIGHT_LIMIT = SCREEN_WIDTH - LEFT_LIMIT
PLAYER_START_POSITION_Y = SCREEN_HEIGHT - 100
DISTANCE_FROM_WALL = 5
GRAVITY = 0.8
TIME_TO_ACCELERATE = 30
FPS = 60